# Generated by Django 3.2.19 on 2023-05-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_author_blog_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Bllog',
        ),
    ]
